# Generated by Django 4.0.6 on 2022-07-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoals',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quickstart.plan'),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='quickstart.user'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='quickstart.brand'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='quickstart.plan'),
        ),
    ]
