# Generated by Django 4.0.6 on 2022-07-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_customergoals_plan_alter_customergoals_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='quickstart.plan', unique=True),
        ),
    ]
