# Generated by Django 4.0.6 on 2022-07-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_promotion_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='quickstart.plan'),
        ),
    ]
